In [1]:
import numpy as np

In [2]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [6]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [8]:
np.random.randn(5,5)

array([[-0.55130482,  0.08283125,  1.08480665, -0.44729942,  1.51423875],
       [ 0.96482534, -1.34045317,  0.5830845 ,  0.19987291, -1.03301959],
       [ 0.53946461,  1.82632427,  0.73161886,  0.95126725,  0.42755411],
       [ 0.22444961,  0.62834799,  0.17128547,  0.12539593, -0.53481648],
       [-0.01760294,  0.26301459, -0.10994081, -1.23422638, -0.03884739]])

In [27]:
r = np.random.randn(4,4)


In [28]:
r

array([[-0.69403534, -1.50166477,  0.33603346, -1.82615091],
       [ 0.51147046, -2.51179988, -0.1234874 ,  1.31666786],
       [-1.07133403, -0.38901862,  1.168204  , -0.44424106],
       [-0.92711379, -1.99452504,  1.38130699, -0.60210761]])

In [29]:
r.T

array([[-0.69403534,  0.51147046, -1.07133403, -0.92711379],
       [-1.50166477, -2.51179988, -0.38901862, -1.99452504],
       [ 0.33603346, -0.1234874 ,  1.168204  ,  1.38130699],
       [-1.82615091,  1.31666786, -0.44424106, -0.60210761]])

In [32]:
r.transpose()

array([[-0.69403534,  0.51147046, -1.07133403, -0.92711379],
       [-1.50166477, -2.51179988, -0.38901862, -1.99452504],
       [ 0.33603346, -0.1234874 ,  1.168204  ,  1.38130699],
       [-1.82615091,  1.31666786, -0.44424106, -0.60210761]])

In [17]:
r.dtype

dtype('float64')

In [31]:
r.reshape(2,8)

array([[-0.69403534, -1.50166477,  0.33603346, -1.82615091,  0.51147046,
        -2.51179988, -0.1234874 ,  1.31666786],
       [-1.07133403, -0.38901862,  1.168204  , -0.44424106, -0.92711379,
        -1.99452504,  1.38130699, -0.60210761]])

In [33]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]


In [34]:
a

[[1, 0], [0, 1]]

In [35]:
b

[[4, 1], [2, 2]]

In [36]:
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [ ]:
np.sort