In [194]:
import numpy as np
import pandas as pd
import time

In [5]:
datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

In [12]:
serie = pd.Series(datos["Población"])
promedio_redondeado = np.round(serie.mean(),decimals=0)
promedio_redondeado

5863277.0

In [13]:
minimo = np.min(serie)
minimo

888124

In [14]:
array1 = np.array(list(range(1,6)))
array2 = np.array(list(range(6,11)))

array_concatenado = np.concatenate([array1,array2])
array_concatenado


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
array_original = np.array(list(range(1,7)))
array_reshaped = array_original.reshape(2,3)

In [29]:
array_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array_original = np.array([[1,2,3],[4,5,6]])

In [33]:
array_aplanado = array_original.flatten()
array_aplanado

array([1, 2, 3, 4, 5, 6])

In [35]:
suma = array_concatenado + array_concatenado
suma

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
transpuesto = array_concatenado.transpose()
transpuesto


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.multiply(array_concatenado,transpuesto)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [43]:
A = np.array(list(range(1,10,2)))
B = np.array([[10],[20],[30],[40],[50]])

In [46]:
resultado = np.add(A,B)
resultado

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59]])

array([1, 3, 5, 7, 9])

In [12]:
lista_grande = list(range(0,1000000,1))
array_grande = np.array(list(range(0,1000000,1)))

In [13]:
inicio = time.time()
lista_grande_cuadrado = [numero**2 for numero in lista_grande]
fin = time.time()
print(fin-inicio)

0.12701725959777832


In [14]:
inicio = time.time()
array_grande_cuadrado = array_grande**2
fin = time.time()
print(fin-inicio)

0.04377555847167969


In [170]:
array = np.genfromtxt('medallas.csv',delimiter=',', skip_header=1)

In [182]:
array_arreglado = array[:,0:4]

In [184]:
# SE INTENTÓ HACER UN CICLO FOR PARA ELIMINAR NANS POR CADA COLUMNA Y LUEGO JUNTAR LAS COLUMNAS
# ESTO FUE UN FRACASO!!
idx_nans = np.array([],dtype=int)
for col in range(len(array_arreglado[0])):
    tmp_a = array_sin_nans[:,col]
    tmp_b = np.where(np.isnan(tmp_a))[0]
    idx_nans = np.concatenate([idx_nans,tmp_b])
idx_nans = np.unique(idx_nans)
array_sin_nans = array_arreglado[~idx_nans,:]
array_sin_nans

array([], shape=(0, 4), dtype=float64)

In [179]:
# EXISTE UNA FORMA DIRECTA PARA ELIMINAR LOS NANS DE CADA FILA DE UN ARRAY 2D
array_sin_nans = array_arreglado[~np.isnan(array_arreglado).any(axis=1)]
array_sin_nans

array([[ 17.,   7.,  22.,  46.],
       [  1.,   1.,   5.,   7.],
       [  1.,   3.,   3.,   7.],
       [  3.,   1.,   3.,   7.],
       [  7.,   6.,   8.,  21.],
       [  3.,   1.,   2.,   6.],
       [  7.,   6.,  11.,  24.],
       [  2.,   4.,   6.,  12.],
       [  3.,   3.,   2.,   8.],
       [  7.,   3.,   5.,  15.],
       [  4.,   4.,   3.,  11.],
       [  3.,   4.,   4.,  11.],
       [  1.,   1.,   4.,   6.],
       [ 39.,  41.,  33., 113.],
       [  1.,   1.,   2.,   4.],
       [  1.,  12.,  11.,  33.],
       [  2.,   5.,   1.,   8.],
       [  1.,  11.,  16.,  37.],
       [ 22.,  21.,  22.,  65.],
       [  2.,   1.,   1.,   4.],
       [  6.,   7.,   7.,   2.],
       [  1.,   2.,   4.,   7.],
       [  1.,   1.,   3.,   5.],
       [  3.,   2.,   2.,   7.],
       [  1.,   1.,   2.,   4.],
       [  4.,   1.,   4.,   9.],
       [ 27.,  14.,  17.,  58.],
       [  4.,   4.,   2.,   1.],
       [  1.,  12.,  14.,  36.],
       [  7.,   6.,   7.,   2.],
       [  

In [90]:
array = np.array([3, np.nan, 7, np.nan, 0, 4.5, np.nan])
sustituir_nans = np.where(np.isnan(array))
sustituir_nans

In [185]:
resultados = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.savetxt('resultados_finales.csv',resultados,delimiter=",",fmt="%d")

In [188]:
df = pd.DataFrame({
    "Nombre": ["Fernando","Miriam"],
    "Edad":[40, 39]
})

In [190]:
prueba = df.to_numpy()
prueba

array([['Fernando', 40],
       ['Miriam', 39]], dtype=object)

In [213]:
mi_dataframe = pd.DataFrame({
    "Frutas": ["Manzana","Banana","Cereza"],
    "Cantidad":[5,8,3]
}) 

mi_dataframe_filtrado = mi_dataframe[mi_dataframe["Cantidad"] > 4]

In [215]:
array_filtrado = mi_dataframe_filtrado.to_numpy()
array_filtrado

array([['Manzana', 5],
       ['Banana', 8]], dtype=object)

In [222]:
mi_array = np.array([[10,40],[20,50],[30,60]])
mi_array

array([[10, 40],
       [20, 50],
       [30, 60]])

In [225]:
df_numeros = pd.DataFrame(mi_array,columns=["Decenas","Centenas"])
df_numeros

Decenas  Centenas
0       10        40
1       20        50
2       30        60