In [3]:
import numpy as np
import pandas as pd

In [5]:
datos = {
    "Ciudad": ["Ciudad de México", "Buenos Aires", "Río de Janeiro", "Lima", "Bogotá", "Santiago de Chile", "São Paulo", "La Habana", "Cancún", "Cartagena"],
    "País": ["México", "Argentina", "Brasil", "Perú", "Colombia", "Chile", "Brasil", "Cuba", "México", "Colombia"],
    "Población": [9265833, 3059574, 6748314, 9756020, 7181663, 6199241, 12333146, 2164182, 888124, 1036671],
    "Visitantes": [21000000, 15000000, 13000000, 9000000, 8000000, 7500000, 20000000, 4000000, 5000000, 3000000]
}

In [12]:
serie = pd.Series(datos["Población"])
promedio_redondeado = np.round(serie.mean(),decimals=0)
promedio_redondeado

5863277.0

In [13]:
minimo = np.min(serie)
minimo

888124

In [14]:
array1 = np.array(list(range(1,6)))
array2 = np.array(list(range(6,11)))

array_concatenado = np.concatenate([array1,array2])
array_concatenado


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
array_original = np.array(list(range(1,7)))
array_reshaped = array_original.reshape(2,3)

In [29]:
array_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
array_original = np.array([[1,2,3],[4,5,6]])

In [33]:
array_aplanado = array_original.flatten()
array_aplanado

array([1, 2, 3, 4, 5, 6])

In [35]:
suma = array_concatenado + array_concatenado
suma

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [41]:
transpuesto = array_concatenado.transpose()
transpuesto


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
np.multiply(array_concatenado,transpuesto)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [43]:
A = np.array(list(range(1,10,2)))
B = np.array([[10],[20],[30],[40],[50]])

In [46]:
resultado = np.add(A,B)
resultado

array([[11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59]])

array([1, 3, 5, 7, 9])